ting funker
jakobbekken/flask-template pull request #2
Opened 2024-09-01 14:04 UTC by AmundDynna

2024-09-01 18:46 UTC, jakobbekken requested changes
Should be simpler in run: only trap and up

2024-09-02 21:05 UTC, AmundDynna commented
Made simpler using only the two functions specified. Ready to push to main

2024-09-02 21:06 UTC, AmundDynna reviewed
test

2024-09-03 11:44 UTC, jakobbekken approved these changes
Much simpler and clearer, looks good!

2024-09-03 11:45 UTC, merged